services:
  backend:
    image: qisitv-backend:server
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        GOPROXY: ${GOPROXY:-https://proxy.golang.org,direct}

  web:
    image: qisitv-web:server
    build:
      context: .
      dockerfile: Dockerfile
